In [1]:
import pandas as pd

movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")
tags = pd.read_csv("tags.csv")
links = pd.read_csv("links.csv")

In [2]:
print("MOVIES")
movies.info()

print("\nRATINGS")
ratings.info()

print("\nTAGS")
tags.info()

print("\nLINKS")
links.info()

MOVIES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  9742 non-null   int64 
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

RATINGS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   userId     100836 non-null  int64  
 1   movieId    100836 non-null  int64  
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

TAGS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   userId     3683 non-null   int64 
 1   m

In [3]:
print("MOVIES")
print(movies.describe())

print("\nRATINGS")
print(ratings.describe())

print("\nTAGS")
print(tags.describe())

print("\nLINKS")
print(links.describe())

MOVIES
             movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

RATINGS
              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

TAGS
            userId        movieId     timestamp
count  3683.000000    3683.000000  3.683000e+03
mean    431.149335   27252.013576  1.320032e+09
std     158.472553   43490.558803  1.721025e+08
min       2.

In [4]:
print("Missing values in movies:")
print(movies.isnull().sum())

print("\nMissing values in ratings:")
print(ratings.isnull().sum())

print("\nMissing values in tags:")
print(tags.isnull().sum())

print("\nMissing values in links:")
print(links.isnull().sum())

Missing values in movies:
movieId    0
title      0
genres     0
dtype: int64

Missing values in ratings:
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

Missing values in tags:
userId       0
movieId      0
tag          0
timestamp    0
dtype: int64

Missing values in links:
movieId    0
imdbId     0
tmdbId     8
dtype: int64


In [5]:
print("تعداد movieId تکراری:")
print(movies["movieId"].duplicated().sum())

print("تعداد title تکراری:")
print(movies["title"].duplicated().sum())

movies[movies["title"].duplicated(keep=False)].sort_values("title")

تعداد movieId تکراری:
0
تعداد title تکراری:
5


,movieId,title,genres
4169,6003,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Thriller
9106,144606,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Romance|Thriller
650,838,Emma (1996),Comedy|Drama|Romance
5601,26958,Emma (1996),Romance
5854,32600,Eros (2004),Drama
9135,147002,Eros (2004),Drama|Romance
2141,2851,Saturn 3 (1980),Adventure|Sci-Fi|Thriller
9468,168358,Saturn 3 (1980),Sci-Fi|Thriller
5931,34048,War of the Worlds (2005),Action|Adventure|Sci-Fi|Thriller
6932,64997,War of the Worlds (2005),Action|Sci-Fi


In [6]:
genres = movies["genres"].str.split("|").explode()

print(genres.value_counts())

genres
Drama                 4361
Comedy                3756
Thriller              1894
Action                1828
Romance               1596
Adventure             1263
Crime                 1199
Sci-Fi                 980
Horror                 978
Fantasy                779
Children               664
Animation              611
Mystery                573
Documentary            440
War                    382
Musical                334
Western                167
IMAX                   158
Film-Noir               87
(no genres listed)      34
Name: count, dtype: int64


In [7]:
movies[movies["genres"] == "(no genres listed)"]

,movieId,title,genres
8517,114335,La cravate (1957),(no genres listed)
8684,122888,Ben-hur (2016),(no genres listed)
8687,122896,Pirates of the Caribbean: Dead Men Tell No Tal...,(no genres listed)
8782,129250,Superfast! (2015),(no genres listed)
8836,132084,Let It Be Me (1995),(no genres listed)
8902,134861,Trevor Noah: African American (2013),(no genres listed)
9033,141131,Guardians (2016),(no genres listed)
9053,141866,Green Room (2015),(no genres listed)
9070,142456,The Brand New Testament (2015),(no genres listed)
9091,143410,Hyena Road,(no genres listed)


In [8]:
movies["genres_clean"] = movies["genres"].str.split("|")

In [9]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb=MultiLabelBinarizer()
genre_matrix=mlb.fit_transform(movies["genres_clean"])

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix=cosine_similarity(genre_matrix)

In [11]:
movie_title = "Toy Story (1995)"
movie_index = movies[movies["title"] == movie_title].index[0]

print(movie_index)

0


In [12]:
similarity_score=list(
    enumerate(similarity_matrix[movie_index]
))
#print(similarity_score)
similarity_score=sorted(
    similarity_score,key=lambda x: x[1],
    reverse=True)

Film=similarity_score[1:11]
for index, score in Film:
    print(
        movies.iloc[index]["title"],
        "→",
        round(score, 3)
    )

Antz (1998) → 1.0
Toy Story 2 (1999) → 1.0
Adventures of Rocky and Bullwinkle, The (2000) → 1.0
Emperor's New Groove, The (2000) → 1.0
Monsters, Inc. (2001) → 1.0
Wild, The (2006) → 1.0
Shrek the Third (2007) → 1.0
Tale of Despereaux, The (2008) → 1.0
Asterix and the Vikings (Astérix et les Vikings) (2006) → 1.0
Turbo (2013) → 1.0


In [13]:
tags_grouped = tags.groupby("movieId")["tag"].apply(
    lambda x: " ".join(x)
).reset_index()

In [14]:
movies = movies.merge(
    tags_grouped,
    on="movieId",
    how="left"
)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
movies["tag"] = movies["tag"].fillna("")
tfidf = TfidfVectorizer()
tag_matrix = tfidf.fit_transform(movies["tag"])
print(tag_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5260 stored elements and shape (9742, 1744)>
  Coords	Values
  (0, 1186)	0.9013892751944387
  (0, 609)	0.43300967028975734
  (1, 548)	0.2993223617805401
  (1, 952)	0.30779663656179057
  (1, 187)	0.3604436401370177
  (1, 617)	0.6900907574071948
  (1, 1307)	0.3341201383494041
  (1, 1714)	0.31286772961538223
  (2, 1023)	0.7071067811865475
  (2, 1120)	0.7071067811865475
  (4, 1216)	0.7306025829401581
  (4, 1279)	0.6828029480026938
  (6, 1279)	1.0
  (10, 1200)	0.647970747235599
  (10, 1219)	0.7616652222117927
  (13, 1200)	0.647970747235599
  (13, 1219)	0.7616652222117927
  (15, 950)	1.0
  (16, 837)	0.7071067811865476
  (16, 116)	0.7071067811865476
  (20, 736)	1.0
  (21, 1379)	0.7160446667214553
  (21, 879)	0.6980544643935458
  (24, 50)	1.0
  (25, 1389)	1.0
  :	:
  (9656, 1057)	0.7071067811865475
  (9656, 133)	0.7071067811865475
  (9681, 610)	0.43679739296587655
  (9681, 329)	0.3981323048895053
  (9681, 1252)	0.5407691201106816
  

In [16]:
from scipy.sparse import hstack
combined_matrix=hstack([genre_matrix,tag_matrix])

In [17]:
similarity_matrix = cosine_similarity(combined_matrix)
#print(similarity_matrix)

In [18]:
rating_stats = ratings.groupby("movieId").agg(
    avg_rating=("rating", "mean"),
    rating_count=("rating", "count")
).reset_index()
#print(rating_stats)

In [19]:
movies = movies.merge(
    rating_stats,
    on="movieId",
    how="left"
)

In [20]:
movies.head(2)

,movieId,title,genres,genres_clean,tag,avg_rating,rating_count
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[Adventure, Animation, Children, Comedy, Fantasy]",pixar pixar fun,3.920930,215.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,"[Adventure, Children, Fantasy]",fantasy magic board game Robin Williams game,3.431818,110.0


In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

rating_matrix = scaler.fit_transform(
    movies[["avg_rating", "rating_count"]]
)

In [22]:
#print(rating_matrix[:5])

In [23]:
from scipy.sparse import hstack

combined_matrix = hstack([
    genre_matrix,
    tag_matrix,
    rating_matrix
])

In [24]:
movie_title = "Toy Story (1995)"
movie_index = movies[movies["title"] == movie_title].index[0]


In [25]:
similarity_score=list(
    enumerate(similarity_matrix[movie_index]
))
#print(similarity_score)
similarity_score=sorted(
    similarity_score,key=lambda x: x[1],
    reverse=True)

Film=similarity_score[1:11]
for index, score in Film:
    print(
        movies.iloc[index]["title"],
        "→",
        round(score, 3)
    )

Toy Story 2 (1999) → 0.93
Antz (1998) → 0.913
Adventures of Rocky and Bullwinkle, The (2000) → 0.913
Emperor's New Groove, The (2000) → 0.913
Monsters, Inc. (2001) → 0.913
Wild, The (2006) → 0.913
Shrek the Third (2007) → 0.913
Tale of Despereaux, The (2008) → 0.913
Asterix and the Vikings (Astérix et les Vikings) (2006) → 0.913
Turbo (2013) → 0.913


In [26]:
print(movies[["avg_rating", "rating_count"]].isna().sum())

avg_rating      18
rating_count    18
dtype: int64


In [27]:
movies[["avg_rating", "rating_count"]] = movies[
    ["avg_rating", "rating_count"]
].fillna(0)

In [28]:
scaler = StandardScaler()

rating_matrix = scaler.fit_transform(
    movies[["avg_rating", "rating_count"]]
)

In [29]:
from sklearn.preprocessing import normalize
from scipy.sparse import csr_matrix

genre_norm = normalize(genre_matrix)
tag_norm = normalize(tag_matrix)
rating_norm = normalize(csr_matrix(rating_matrix))

In [30]:
weighted_matrix = hstack([
    genre_norm * 0.4,
    tag_norm * 0.4,
    rating_norm * 0.2
])

In [31]:
#پیشنهاد فیلم به کاربر بر اساس سلیقه مشابه کاربر هایی که
#چند فیلم را دیدن و رای یکسانی به انها دادن

In [32]:
#اابتدا باید جدولی بسازیم که
#سطر های ان کاربران و ستون های ان فیلم ها و داخل سلول ها
#نظرات کاربر به ان فیلم ها باشد

In [33]:
user_movie_matrix=ratings.pivot_table(
    index="userId",
    columns="movieId",
    values="rating"
)
     

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

user_similarity = cosine_similarity(
    user_movie_matrix.fillna(0)
)

print(user_similarity)

[[1.         0.02728287 0.05972026 ... 0.29109737 0.09357193 0.14532081]
 [0.02728287 1.         0.         ... 0.04621095 0.0275654  0.10242675]
 [0.05972026 0.         1.         ... 0.02112846 0.         0.03211875]
 ...
 [0.29109737 0.04621095 0.02112846 ... 1.         0.12199271 0.32205486]
 [0.09357193 0.0275654  0.         ... 0.12199271 1.         0.05322546]
 [0.14532081 0.10242675 0.03211875 ... 0.32205486 0.05322546 1.        ]]


In [35]:
user_id = 1

user_index = user_movie_matrix.index.get_loc(user_id)

similar_users = list(
    enumerate(user_similarity[user_index])
)

similar_users = sorted(
    similar_users,
    key=lambda x: x[1],
    reverse=True
)

similar_users = similar_users[1:11]

for index, score in similar_users:
    similar_user_id = user_movie_matrix.index[index]
    
    print(
        "User:", similar_user_id,
        "→",
        round(score, 3)
    )

User: 266 → 0.357
User: 313 → 0.352
User: 368 → 0.345
User: 57 → 0.345
User: 91 → 0.335
User: 469 → 0.331
User: 39 → 0.33
User: 288 → 0.33
User: 452 → 0.328
User: 45 → 0.328


In [36]:
#ابتدا این ۱۰ نفر را وارد یک لیست میکنیم
top_10_users = []

for index, similarity in similar_users:
    similar_user_id = user_movie_matrix.index[index]
    
    top_10_users.append(similar_user_id)

print(top_10_users)

[np.int64(266), np.int64(313), np.int64(368), np.int64(57), np.int64(91), np.int64(469), np.int64(39), np.int64(288), np.int64(452), np.int64(45)]


In [37]:
#فیلم هایی ک این ۱۰ نفر دیده اند را جمع میکنیم در یک لیست
candidate_movies = []
for user_id in top_10_users:
    user_movies = user_movie_matrix.loc[user_id].dropna().index
    candidate_movies.extend(user_movies)


In [38]:
#فیلم هایی ک کاربر یک دیده را از اون لیست پاک میکنیم
user_1_movies = user_movie_matrix.loc[1].dropna().index
new_candidate_movies = []

for movie_id in candidate_movies:
    
    if movie_id not in user_1_movies:
        
        new_candidate_movies.append(movie_id)
print(new_candidate_movies)

[16, 17, 21, 24, 32, 39, 45, 64, 69, 95, 132, 135, 145, 198, 288, 353, 368, 377, 440, 474, 476, 493, 514, 541, 551, 555, 589, 694, 778, 785, 924, 1036, 1079, 1093, 1171, 1199, 1200, 1215, 1242, 1259, 1261, 1266, 1285, 1288, 1297, 1356, 1374, 1375, 1376, 1394, 1405, 1466, 1476, 1485, 1527, 1597, 1610, 1614, 1641, 1663, 1722, 1772, 1784, 1866, 1883, 1884, 1911, 1912, 1923, 1968, 2064, 2097, 2167, 2194, 2195, 2249, 2278, 2288, 2300, 2302, 2321, 2355, 2384, 2396, 2428, 2471, 2490, 2539, 2560, 2599, 2605, 2683, 2702, 2706, 2710, 2712, 2770, 2791, 2804, 2812, 2863, 2890, 2918, 2968, 3016, 3020, 3039, 3060, 3108, 3113, 3142, 3156, 3265, 10, 29, 32, 39, 76, 165, 170, 172, 188, 196, 253, 293, 318, 332, 353, 377, 379, 380, 382, 405, 442, 474, 512, 519, 541, 589, 610, 737, 750, 858, 866, 880, 912, 920, 924, 968, 991, 999, 1036, 1037, 1047, 1059, 1125, 1129, 1199, 1200, 1212, 1215, 1221, 1235, 1247, 1249, 1261, 1274, 1285, 1287, 1301, 1320, 1339, 1344, 1345, 1347, 1350, 1356, 1371, 1372, 1374, 137

In [57]:
#حالا این فیلم هارا میشماریم و فیلم هایی ک بیشترین تکرار را
#دارند ۱۰ تای اول رو پیشنهاد میدهیم
movie_counts = pd.Series(new_candidate_movies).value_counts()
#print(movie_counts)
top_10=movie_counts[:10]
#print(top_10)

In [58]:
for movie_id, count in top_10.items():

    title = movies.loc[
        movies["movieId"] == movie_id,
        "title"
    ].iloc[0]

    print(title, "→", count, "نفر")

Breakfast Club, The (1985) → 10 نفر
Hunt for Red October, The (1990) → 10 نفر
Die Hard (1988) → 10 نفر
2001: A Space Odyssey (1968) → 10 نفر
Terminator 2: Judgment Day (1991) → 10 نفر
Aliens (1986) → 9 نفر
Star Trek III: The Search for Spock (1984) → 9 نفر
Sixth Sense, The (1999) → 9 نفر
Airplane! (1980) → 9 نفر
Star Trek II: The Wrath of Khan (1982) → 9 نفر


In [62]:
#ساخت تابع برای این موضوع
def recommend_movies(user_id):
    user_index=user_movie_matrix.index.get_loc(user_id)
    similar_users = list(
    enumerate(user_similarity[user_index])
    )

    similar_users = sorted(
    similar_users,
    key=lambda x: x[1],
    reverse=True
    )

    similar_users = similar_users[1:11]
    top_10_users = []

    for index, similarity in similar_users:
        similar_user_id = user_movie_matrix.index[index]
    
        top_10_users.append(similar_user_id)
    candidate_movies = []
    for similar_user in top_10_users:
        user_movies = user_movie_matrix.loc[user_id].dropna().index
        candidate_movies.extend(user_movies)
        
    user_movies = user_movie_matrix.loc[user_id].dropna().index
    new_candidate_movies = []

    for movie_id in candidate_movies:
    
        if movie_id not in user_1_movies:
        
            new_candidate_movies.append(movie_id)
    movie_counts = pd.Series(new_candidate_movies).value_counts()
    top_10=movie_counts[:10]
    
    for movie_id, count in top_10.items():

        title = movies.loc[
            movies["movieId"] == movie_id,
            "title"
        ].iloc[0]
        print(
            title,
            "→",
            count,
            

        )

In [63]:
recommend_movies(50)

Twelve Monkeys (a.k.a. 12 Monkeys) (1995) → 10 نفر از کاربران مشابه
Looper (2012) → 10 نفر از کاربران مشابه
Good Day to Die Hard, A (2013) → 10 نفر از کاربران مشابه
Django Unchained (2012) → 10 نفر از کاربران مشابه
Life of Pi (2012) → 10 نفر از کاربران مشابه
Flight (2012) → 10 نفر از کاربران مشابه
Argo (2012) → 10 نفر از کاربران مشابه
Hotel Transylvania (2012) → 10 نفر از کاربران مشابه
Samsara (2011) → 10 نفر از کاربران مشابه
Great Gatsby, The (2013) → 10 نفر از کاربران مشابه
